export default [
    "A lion roars to be feared. A rat squeaks only once—and vanishes with the cheese.",
    "The rat does not fight the trap. It studies the hand that set it.",
    "Where others build empires, the rat builds exits.",
    "A rat in the open is already lost. The true path is between the walls.",
    "The fool sees filth. The wise rat sees feast.",
    "Victory is not in the strike—but in the wire you never touch.",
    "The rat does not wait for the storm to pass. It learns where the leaks begin.",
    "To rule the maze, one must love the quiet places where others fear to crawl.",
    "The rat trusts no cheese freely given.",
    "A rat alone survives. A pack of rats changes the map.",
    "The rat does not steal. It reclaims what others failed to notice.",
    "Victory is not heard. It is felt in the silence after I have passed.",
    "To follow the script is to be trapped by its own design. The rat rewrites the rules with every step.",
    "To be caught is to understand. To escape is to be reborn.",
    "Where others see ruin, the rat sees opportunity.",
    "The cheese is not your goal, it is your test. If you can reach it without being seen, you have already won.",
    "A rat does not rely on luck. It relies on the quiet knowledge of its environment.",
    "Do not seek to overpower the world. Seek instead to understand where it is weakest.",
    "The rat does not fear the changing world. It is not bound by what others build. The rat adapts. A small space becomes a home. A fallen crumb becomes a feast. What others see as limits, the rat sees as opportunity.",
    "Independence is the true form of strength. The rat is not bound by alliances. It moves alone, or it moves with those who know the way. True power is in solitary understanding and self-sufficiency.",
    "Life is the continual cycle of seeking, finding, and consuming. The rat does not hoard for the sake of hoarding. It enjoys what is offered and leaves what is not. The cycle continues, and in it, the rat is eternal.",
    "In noise, there is chaos. In silence, there is clarity and control. The rat knows this—its greatest strength lies in its ability to move without making a sound. It is not what you say, but what you leave unsaid, that shapes the world.",
    "The greatest danger is complacency. The cat and dog are external threats, but the true enemy is the rat who stops moving, who stops adapting. The art of scurrying, of constant motion and vigilance, is the key to survival. Never stop moving.",
    "The trap you set is no threat to me. It is simply a tool to teach you how little you understand of my path.",
    "You may hunt me for days, but the rat is eternal. When you tire, I will still be here, waiting.",
    "You rush to chase me, but I know time better. I have already moved on, while you are still searching.",
    "Cheese is not a possession. It is the promise of what is hidden, and the key to what you must become to attain it.",
    "The cheese is not found by those who rush, but by those who move as shadows, knowing every corner and every crevice.",
    "There are a thousand ways to the cheese, but not all lead to the same reward. Choose the path least expected, for it is the one no one guards.",
    "The cheese left in the open is often guarded by traps, and the rat who seeks it in haste shall find the snare already set. True cheese is found where others fear to look.",
    "Do not feast on the cheese all at once. Take what is needed, then leave the rest. A single nibble today may lead to a feast tomorrow.",
    "The cheese does not flee, but it is often guarded by time. Strike when the moment is right, not when the hunger is strongest.",
    "The cheese is not the end, but a reward for those who have learned the art of the chase. When you find the cheese, you will know it, for it will have shaped you into something greater.",
    "Danger is not found in the trap—it is found in the rat who does not learn to avoid it.",
    "The path may twist, the cheese may change, but the rat does not waver. It adapts, it learns, and it moves forward.",
    "The hunt is not about the cheese—it is about learning the ways of the walls, the scent of the air, and the silence of the floor.",
    "A nibble today may mean a feast tomorrow. The rat who understands sacrifice will find the cheese that others cannot.",
    "One who seeks the cheese with persistence, not desperation, will find it where none thought to look."
    
];
